<Project>
  <PropertyGroup>
    <Copyright>Copyright © 2013-$([System.DateTime]::Now.Year) Akka.NET Team</Copyright>
    <Authors>Akka.NET Team</Authors>
    <VersionPrefix>1.5.52</VersionPrefix>
    <PackageReleaseNotes>* Update to [Akka.NET v1.5.52](https://github.com/akkadotnet/akka.net/releases/tag/1.5.52)
* Update to [Akka.Hosting v1.5.52](https://github.com/akkadotnet/Akka.Hosting/releases/tag/1.5.52)</PackageReleaseNotes>
    <PackageIconUrl>https://getakka.net/images/akkalogo.png</PackageIconUrl>
    <PackageProjectUrl>https://github.com/akkadotnet/Akka.Management</PackageProjectUrl>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <PropertyGroup>
    <AkkaPackageTags>akka;actors;actor model;Akka;concurrency;service discovery;cluster;clustering;</AkkaPackageTags>
    <LibraryFramework>netstandard2.0</LibraryFramework>
    <NetFramework>net6.0</NetFramework>
    <TestsNet>net9.0</TestsNet>
    <XunitVersion>2.9.3</XunitVersion>
    <XUnitRunnerVersion>3.1.0</XUnitRunnerVersion>
    <CoverletVersion>6.0.4</CoverletVersion>
    <FluentAssertionVersion>7.0.0</FluentAssertionVersion>
    <TestSdkVersion>17.13.0</TestSdkVersion>
    <WireMockVersion>1.8.4</WireMockVersion>
    <AkkaVersion>1.5.52</AkkaVersion>
    <AkkaHostingVersion>1.5.55</AkkaHostingVersion>
    <PbmVersion>1.4.5</PbmVersion>
    <KubernetesClientVersionNet>17.0.14</KubernetesClientVersionNet>
    <MicrosoftExtensionsVersion>[6.0.*,)</MicrosoftExtensionsVersion>
    <AzureIdentityVersion>1.14.2</AzureIdentityVersion>
    <ProtobufVersion>3.30.2</ProtobufVersion>
    <GrpcToolsVersion>2.71.0</GrpcToolsVersion>
  </PropertyGroup>
  <!-- SourceLink support for all Akka.NET projects -->
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
  </ItemGroup>
  <PropertyGroup>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <!-- Optional: Embed source files that are not tracked by the source control manager in the PDB -->
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <!-- Optional: Build symbol package (.snupkg) to distribute the PDB containing Source Link -->
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
</Project>
