######################################################
# Akka Service Discovery DNS Config                  #
######################################################

akka.discovery {
  # Set the following in your application.conf if you want to use this discovery mechanism:
  method = akka-dns
  akka-dns {
    class = "Akka.Discovery.Dns.DnsServiceDiscovery, Akka.Discovery.Dns"
    
    # How long to wait for a DNS query to resolve before timing out
    resolve-timeout = 5s
    
    # When true, failing to resolve a service name will be logged as a warning
    verbose-failure-logging = on
  }
}

# DNS resolver configuration
akka.io.dns {
  # Default resolver is inet-address (uses System.Net.Dns.GetHostAddresses)
  # For SRV record resolution use async-dns and add akka.io.dns.async-dns config as below
  resolver = async-dns
  
  # Async DNS resolver using direct DNS query (not using System.Net.Dns.GetHostAddresses)
  async-dns {
    class = "Akka.Discovery.Dns.Internal.DnsClient, Akka.Discovery.Dns"
    provider-object = "Akka.Discovery.Dns.Internal.AsyncDnsProvider, Akka.Discovery.Dns"
    # The hostname and/or IPv4/v6 address list of the nameservers to use
    # Port is optional, defaults to 53
    nameservers = [ "127.0.0.1:53"; "my-dns.example.com"; "[::1]:53" ]
  }
}
