<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\..\xunitSettings.props" />
  <PropertyGroup>    
    <TargetFramework>$(TestsNet)</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Akka.Hosting.TestKit" />
    <PackageReference Include="Akka.Cluster.Hosting" />
    <PackageReference Include="Akka.Remote.Hosting" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Akka.TestKit.Xunit2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Akka.Management\Akka.Management.csproj" />
  </ItemGroup>

</Project>
