<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
	<TargetFrameworks>$(LibraryFramework);$(NetFramework)</TargetFrameworks>
		<Description>Akka.NET coordination module for Microsoft Azure</Description>
		<PackageTags>$(AkkaPackageTags);Azure;</PackageTags>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="protobuf\LeaseResource.proto" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Akka.Discovery" />
		<PackageReference Include="Akka.Cluster" />
		<PackageReference Include="Akka.Hosting" />
		<PackageReference Include="Akka.Cluster.Hosting" />
		<PackageReference Include="Azure.Identity" />
		<PackageReference Include="Azure.Storage.Blobs" />
		<PackageReference Include="Google.Protobuf" />
		<PackageReference Include="Grpc.Tools">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="reference.conf" />
	</ItemGroup>

	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
	  <InternalsVisibleTo Include="Akka.Coordination.Azure.Tests" />
	</ItemGroup>
</Project>
