# Pull request validation for Windows against the `dev` and `master` branches
# See https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema for reference
trigger:
  batch: true
  branches:
    include:
      - dev
      - master
      - feature/*
      - v1.*
      - gh-readonly-queue/*
     
pr:
  autoCancel: true # indicates whether additional pushes to a PR should cancel in-progress runs for the same PR. Defaults to true
  branches:
    include: [ dev, master, feature/*, v1.*] # branch names which will trigger a build

name: $(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

jobs:
  - template: azure-pipeline.template.yaml
    parameters:
      name: 'windows_pr'
      displayName: 'Windows PR Validation'
      vmImage: 'windows-latest'
      scriptFileName: build.cmd
      scriptArgs: all
      outputDirectory: 'bin/nuget'
      artifactName: 'nuget_pack-$(Build.BuildId)'
  - template: azure-pipeline.template.yaml
    parameters:
      name: 'linux_pr'
      displayName: 'Linux PR Validation'
      vmImage: 'ubuntu-latest'
      scriptFileName: ./build.sh
      scriptArgs: all
      outputDirectory: 'bin/nuget'
      artifactName: 'nuget_pack-$(Build.BuildId)'
