<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(LibraryFramework);$(NetFramework)</TargetFrameworks>
        <Description>Akka.NET Service Discovery for Azure-hosted services. Works with App Service, Container Apps, and more.</Description>
        <PackageTags>$(AkkaPackageTags);Azure;AppService;Service Discovery;Azure Table Storage</PackageTags>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
      <None Remove="protobuf\ClusterMemberProto.proto" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Akka.Discovery" />
      <PackageReference Include="Akka.Cluster" />
      <PackageReference Include="Akka.Hosting" />
      <PackageReference Include="Azure.Data.Tables" />
      <PackageReference Include="Azure.Identity" />
      <PackageReference Include="Google.Protobuf" />
      <PackageReference Include="Grpc.Tools">
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        <PrivateAssets>all</PrivateAssets>
      </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <Protobuf Include="protobuf\ClusterMemberProto.proto" Access="Internal" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="reference.conf" />
      <EmbeddedResource Include="reference.conf" />
    </ItemGroup>

    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="\" />
    </ItemGroup>
</Project>
